version: "3.9"

services:
  gateway:
    image: nginx:alpine
    ports:
      - "${TEAM_PORT}:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      # used by your nginx config to talk to Core (inside docker network)
      - CORE_BASE_URL=${CORE_BASE_URL}
    depends_on:
      - app
    networks:
      - app404

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      S3_ENDPOINT_URL: "http://minio:9000"
      S3_BUCKET: "${MINIO_BUCKET}"
      S3_REGION: "${MINIO_REGION_NAME}"
      AWS_ACCESS_KEY_ID: "${MINIO_ROOT_USER}"
      AWS_SECRET_ACCESS_KEY: "${MINIO_ROOT_PASSWORD}"
      S3_USE_SSL: "false"
      URL_DATABASE_TEAM8: ${URL_DATABASE_TEAM8}
    networks:
      - app404
    depends_on:
      postgres:
        condition: service_healthy

  minio:
    image: ${MINIO_IMAGE}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      MINIO_DEFAULT_BUCKETS: "${MINIO_BUCKET}:${MINIO_BUCKET_POLICY}"
      MINIO_REGION_NAME: "${MINIO_REGION_NAME}"
    volumes:
      - minio-data:/bitnami/minio/data
    networks:
      - app404

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TEAM8_POSTGRES_DB}
      POSTGRES_USER: ${TEAM8_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEAM8_POSTGRES_PASSWORD}
    volumes:
      - team8-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEAM8_POSTGRES_USER} -d ${TEAM8_POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 15
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net

volumes:
  minio-data:
  team8-pgdata:
