services:
  gateway:
    image: nginx:alpine
    ports:
      - "9151:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - CORE_BASE_URL=http://core:8000
    networks:
      - app404
    depends_on:
      - trip-plan

  trip-plan:
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app404
    volumes:
      - ./tripPlanService:/app

networks:
  app404:
    external: true
    name: app404_net