services:
  gateway:
    image: nginx:alpine
    ports:
      - "${TEAM_PORT}:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - CORE_BASE_URL=http://core:8000
    networks:
      - app404
  #   depends_on:
  #     - frontend
  #     - backend

  # frontend:
  #   image: traefik/whoami
  #   command: ["-port=5173"]
  #   networks:
  #     - app404

  # backend:
  #   image: traefik/whoami
  #   command: ["-port=3000"]
  #   networks:
  #     - app404

networks:
  app404:
    external: true
    name: app404_net